### ISSUE TITLE
不与0.4.1版本的RealSurvival兼容

### ISSUE THREAD

**Issue by bowencraft** [SchoolUniform/CropPlus#1]
`java.lang.NoClassDefFoundError: com/outlook/schooluniformsama/api/Season
`

现在最后支持到的版本大概是0.3.8
如果这个插件仍在继续被支持吗？

**Comment by SmileYik** [comment]
刚刚更新啦: https://github.com/SmileYik/CropPlus/commit/05169dddde2cd72e5390cc6d915374814eb064a8
具体可以到mcbbs发布帖下载哟.
